services:
    # Twig extension
    jgp_ajax_blocks.twig_extension:
        class: Jagilpe\AjaxBlocksBundle\Twig\AjaxBlocksExtension
        public: true
        tags:
            - { name: twig.extension }

    # Event listener
    jgp_ajax_tools.ajax_block_controller_listener:
        class: Jagilpe\AjaxBlocksBundle\EventListener\AjaxBlockControllerEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller }